### ISSUE TITLE
Epic: HEAL Harmonization

### ISSUE THREAD

**Issue by hhiles** [helxplatform/dug#224]
### Introduction

The HEAL program includes hundreds of projects generating highly diverse data sets. 

RTI and RENCI, the **HEAL Stewards**, will
* Use semantic knowledge graphs to link data from disparate studies to facilitate analysis.
* Perform preliminary harmonization of data sets towards the HEAL Common Data Elements (CDE)s
* Provide user friendly interfaces with a biological lens on the data.

### HEAL Harmonization

To accomplish this:

* [ ] Ingest HEAL CDEs 
  * [x] Create (or [locate](https://app.box.com/folder/91968827078?s=t4i32dmqxx941xu079wtc2okly8ixfyn)) machine readable versions of the HEAL CDEs @gaurav
  * [x] Discuss w/NIH how to publish machine readable HEAL CDEs @gaurav 
  * [x] Annotate with controlled vocabulary and ontology identifiers @gaurav
    * [x] Map provided NCI Metathesaurus ids to Human Phenotype Ontology (etc) identifiers @gaurav 
    * [x] Annotate HEAL CDEs with Monarch's BioLink API SciGraph Named Entity Recognition service (NER) @gaurav
    * [ ] Look into alternate NER tools for finding terms in HEAL CDEs (https://github.com/helxplatform/development/issues/804) @gaurav 
    * [x] Convert to Biolink and KGX compliant artifacts @gaurav 
    * [x] Apply the SRI Normalizer to use Translator preferred identifiers @YaphetKG @gaurav
    * [ ] Clean up SciGraph annotations and resend cleaned KGX files to Yaphet @gaurav
  * [x] Optimize TranQL queries to take advantage of Redisgraph performance. @YaphetKG 
  * [x] Create new harmonization and translational TranQL queries to @YaphetKG 
  * [x] Link variables through phenotypes, chemicals, diseases to CDEs @YaphetKG 
  * [ ] Index, recording harmonization connections to enable display
* [x] Ingest HEAL study data as it becomes available @waTeim  
  * [x] Begin with
    * [x] The SPARC [knowledge graph](https://cassava.ucsd.edu/sparc//exports/). @HowardLander 
    * [x] NIDA (as transformed/provided by Comp 2) @warrenstephens 
  * [x] Create a Dug parser for each data format.
* [ ] Update the HeLx/Dug UI to @mbwatson 
   * [ ] Render 
     * [ ] An "All" tab for generic search results including lexical matches.
     * [ ] A "Harmonized" tab for everything else with markers for CDE, PhenX, Biolink, and other groupings.
   * [x] Allow deployment with or without
     * [x] Authentication
     * [x] App Workspaces
  * [x] Present an information dense display minimizing paging and scrolling

### Design

![image](https://user-images.githubusercontent.com/306971/124320878-b410e100-db4a-11eb-93fb-0cf829f30c77.png)

@alexwaldrop @jcheadle-rti 

### PM Tracking

@hhiles to work with @vgardner-renci and Kathy to report on the following HEAL epics and their related GitHub tickets; give updates directly to PMs or plug into [Monday.com](https://renci-teams.monday.com/boards/2390983090)

* Index Data Dictionaries 
  * #169
  * #768
* Develop Automated Curation and Search
  * #868 
  * #725
* Enable Cloud Based Semantic Search
  * #884

**Comment by hhiles** [comment]
View past comments and figures for this work https://github.com/helxplatform/development/issues/742

**Comment by krobasky** [comment]
@hhiles Questions:
1. Is it possible to give me at least read-access to helxplatform/development repo so that I can see a) context of this ticket on 742, and the PM tracking tickets 169, 768?
2. Alex is gathering metadata using either CEDAR or REDCap, and I could be wrong but I believe this is outside the RTI CDE, HEAL CDE, and PhenX ingestion. Should this be added to the design?
3. I don't see a task or owner for creating, integrating, and deploying the HEAL pipeline, handler & test suite, or is that part of the "Create a Dug parser for each data format" task owned by 'waTeim'?

**Comment by hhiles** [comment]
@krobasky 
1. Done - read access
2. I can't comment on what should change with the design - this is something that could be discussed at a future scrum @alexwaldrop 
3. I read through the descriptions of the 3 epics in Monday as they relate to the 3 above (epic 20, 22, and 23), and I am not entirely sure which one `creating, integrating, and deploying the HEAL pipeline, handler & test suite` relates to. Can you clarify?

**Comment by krobasky** [comment]
@hhiles 

I think we've come to the conclusion that the Monday epics don't map well operational tasks, so I'm not able to answer your question other than saying it maps broadly across all the epics. 

But before we go further, let me confirm - 

@alexwaldrop 

Do I correctly understand that a HEAL parser needs to be created (with handler & test suite) in order to deploy the HEAL data dictionaries to heal.renci.org? Or are you thinking there will need to be one parser per dictionary provided by each PI?

**Comment by hhiles** [comment]
@cbizon @YaphetKG @gaurav I'd like to avoid just blanket recreating this ticket in jira - can we identify what components of this work still need to be done, and what still needs to be recreated?

**Comment by hhiles** [comment]
@mbwatson and @YaphetKG - what is left to do on this ticket?

**Comment by hhiles** [comment]
most of this ticket is in jira or is done. confirming with @mbwatson on the UI portion
